Repository wonderlandpark/dokdo, pull requests merged in 2020-12, with the labels that each got.

#2 v0.1 Release
  .eslintrc.js
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/workflows/reviewdog.yml
  .github/workflows/testing-cron.yml
  .github/workflows/testing.yml
  .gitignore
  README.md
  assets/dokdo.png
  assets/logo.png
  assets/shard.png
  dokdo.gif
  examples/bot.js
  examples/config.example.js
  examples/shard.js
  package.json
  src/commands/cat.js
  src/commands/curl.js
  src/commands/exec.js
  src/commands/index.js
  src/commands/js.js
  src/commands/jsi.js
  src/commands/main.js
  src/commands/shard.js
  src/index.js
  src/utils/KillChildrenProcess.ps1
  src/utils/ProcessManager.js
  src/utils/codeBlock.js
  src/utils/count.js
  src/utils/hljs.js
  src/utils/index.js
  src/utils/isinstance.js
  src/utils/js.js
  src/utils/jsi.js
  src/utils/react.js
  src/utils/shard.js
  src/utils/system.js
  src/utils/table.js
  src/utils/type.js
  test/Utils.codeBlock.test.js
  test/Utils.count.test.js
  test/Utils.hljs.test.js
  typings/index.d.ts
  typings/test.ts
  yarn.lock
Labels: meta: cleanup, meta: code style, meta: dependencies, meta: document, meta: tests, semver: major

#30 fix: add aliases param to option
  src/index.js
Labels: semver: patch, type: bugfix

#32 fix: prevent noPerm not being a Function
  src/index.js
Labels: semver: patch
