Repository wonderlandpark/dokdo, pull requests merged in 2020-11, with the labels that each got.

#1 fix(main|shard): Missing awaits
  src/commands/main.js
  src/commands/shard.js
Labels: p: low, semver: patch, type: bugfix

#6 feat: supporting kurasuta shard manager
  src/commands/main.js
Labels: semver: patch, type: enhancement

#10 refactor: refactor and type codes
  README.md
  assets/dokdo.png
  assets/logo.png
  package.json
  src/commands/exec.js
  src/commands/js.js
  src/commands/jsi.js
  src/commands/main.js
  src/commands/shard.js
  src/index.js
  src/utils/ProcessManager.js
  src/utils/codeBlock.js
  src/utils/isinstance.js
  src/utils/system.js
  src/utils/table.js
  typings/index.d.ts
  typings/test.ts
Labels: meta: code style, meta: document, meta: refactor, semver: patch
