Repository wonderlandpark/dokdo, pull requests merged in 2021-01, with the labels that each got.

#52 Move discord.js dependency to DevDependency
  package.json
Labels: semver: minor, type: bugfix

#67 v0.2 Release
  README.md
  assets/dokdo.gif
  package.json
  src/commands/shard.js
  src/index.js
  yarn.lock
Labels: semver: minor

#68 WHATS THE PROBLEM WITH YOU?
  package.json
Labels: semver: N/A
