Repository wonderlandpark/dokdo, pull requests merged in 2021-07, with the labels that each got.

#221 fix: change ready event once
  src/index.js
Labels: semver: patch

#226 Readme changes
  README.md
Labels: meta: document, semver: N/A

#225 Fix secret not hidden at special char
  package.json
  src/utils/ProcessManager.js
  src/utils/index.js
  src/utils/regexpEscape.js
  test/Utils.ProcessManager.test.js
Labels: semver: patch, type: bugfix

#244 Feature/djs docs command
  src/commands/docs.js
  src/commands/index.js
  src/index.js
  src/utils/djsDocs.js
  src/utils/index.js
Labels: semver: minor

#247 Release/0.4
  .gitignore
  package.json
Labels: semver: minor

#249 feat: use discord timestamp message formatting instead of dayjs
  package.json
  src/commands/main.js
  src/utils/index.js
  src/utils/relativeTime.js
  src/utils/system.js
  yarn.lock
Labels: semver: patch, type: enhancement
